all:IO.c
	gcc IO.c -o IO.out
	gcc FM_M1.c -o FM_M1.outgcc 
	gcc FM_linux.c -o FM_linux.out
	gcc memory_test.c -o memory_test.out
clean:
	rm -f IO.out
	rm -f FM_M1.out
	rm -f FM_linux.out
	rm -f memory_test.out
