all:shell.cpp noop.cpp number.cpp removetag.cpp removetag0.cpp
	g++ -o npshell shell.cpp
	g++ -o bin/noop noop.cpp
	g++ -o bin/number number.cpp
	g++ -o bin/removetag removetag.cpp
	g++ -o bin/removetag0 removetag0.cpp
clean:
	rm -f npshell
	rm -f bin/noop
	rm -f bin/number
	rm -f bin/removetag
	rm -f bin/removetag0